#!/usr/bin/env python3
import sys

if len(sys.argv) < 2:
  print("Usage: %s <input hex file> <output binary file>" % sys.argv[0])
  exit()

def hex2bin(fileName):
  data = []
  f = open(fileName, 'r')
  for line in f:
    # get the length of data
    lineLen = int(line[1:3], 16)
    # make sure it is a data line
    if lineLen > 0 and line[7:9] == '00':
      # parse the data into an array
      bindata = line[9:9 + 2 * lineLen]
      for i in range(lineLen):
        data.append(int(bindata[i:i+2], 16))
  return bytearray(data)

d = hex2bin(sys.argv[1])

f = open(sys.argv[2], 'wb')
f.write(bytes(d))
f.close()